name: React.js CI/CD
on:
  push:
    branches:
      main
      dev
      staging
     
  pull_request:
    branches: 
      main
      dev
      staging
jobs:
  build:
    runs-on: ubuntu 20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm start
      - name: Build React App
        run: npm run build
      - name: Run Tests
        run: npm start
